dr/torneio
cesium/codeweek18 pull request #7
Opened 2018-09-27 19:52 UTC by ribeiropdiogo

2018-09-27 20:10 UTC, nelsonmestevao requested changes

2018-09-27 20:10 UTC, nelsonmestevao commented on Gemfile.lock
> +GEM
Remove this file.

2018-09-27 20:10 UTC, nelsonmestevao commented on _includes/tickets.html
> +            <p>XX Outubro</p>
A data é 17 de Outubro.

2018-09-27 20:10 UTC, nelsonmestevao commented on _includes/tickets.html
> +          <a href="http://www.cesium.di.uminho.pt/activities" class="btn btn-common">PARTICIPAR</a>
Isto devia ser uma variável do evento torneio para depois ser fácil de mudar o link de inscrição.

2018-09-27 20:10 UTC, nelsonmestevao commented on _includes/head.html
> +  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
Remove this and make it another pull request. One that also changes all the icons you can find.

2018-09-27 20:23 UTC, ribeiropdiogo commented on _includes/head.html
> +  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
depois é preciso font awesome por causa dos simbolos dos premios

2018-09-27 20:24 UTC, ribeiropdiogo commented on _includes/tickets.html
> +            <p>XX Outubro</p>
e local?

2018-09-29 18:36 UTC, nelsonmestevao commented on Gemfile.lock
> +GEM
@ribeiropdiogo remove this file, please.

2018-10-02 10:11 UTC, closed without merging